### ISSUE TITLE
Can not order the genes according to alignment similarity statistics

### ISSUE THREAD

**Issue by cynthier** [Teichlab/Genes2Genes#10]
Hi dinithins,

I finished the alignment and wanted to order the genes according to the alignment similarity statistics. And the error below was reported. This worked well when I used several genes. This time I used 3000 variable genes.

`aligner`
<genes2genes.Main.RefQueryAligner at 0x2b963b645eb0>
`aligner.get_stat_df()`

AttributeError                            Traceback (most recent call last)
Cell In[118], line 1
----> 1 df = aligner.get_stat_df() # ordered genes according to alignment similarity statistics 

File [~/conda/pkgs/python_envs/lib/python3.8/site-packages/genes2genes/Main.py:471](http://127.0.0.1:1964/lab/tree/projects/HDAC/4_trajectory_analysis/conda/pkgs/python_envs/lib/python3.8/site-packages/genes2genes/Main.py#line=470), in RefQueryAligner.get_stat_df(self)
    468     qgex = np.asarray(self.query_mat.loc[:,g])        
    469     l2fc.append(np.log2(np.mean(rgex)/np.mean(qgex))) 
--> 471 df = pd.DataFrame([self.gene_list, match_percentages, opt_alignment_costs, l2fc]).transpose()
    472 df.columns = ['Gene','alignment_similarity_percentage', 'opt_alignment_cost','l2fc']
    473 df.set_index('Gene')

File [~/conda/pkgs/python_envs/lib/python3.8/site-packages/pandas/core/frame.py:782](http://127.0.0.1:1964/lab/tree/projects/HDAC/4_trajectory_analysis/conda/pkgs/python_envs/lib/python3.8/site-packages/pandas/core/frame.py#line=781), in DataFrame.__init__(self, data, index, columns, dtype, copy)
    780     if columns is not None:
    781         columns = ensure_index(columns)
--> 782     arrays, columns, index = nested_data_to_arrays(
    783         # error: Argument 3 to "nested_data_to_arrays" has incompatible
    784         # type "Optional[Collection[Any]]"; expected "Optional[Index]"
    785         data,
    786         columns,
    787         index,  # type: ignore[arg-type]
    788         dtype,
    789     )
    790     mgr = arrays_to_mgr(
    791         arrays,
    792         columns,
   (...)
    795         typ=manager,
    796     )
    797 else:

File [~/conda/pkgs/python_envs/lib/python3.8/site-packages/pandas/core/internals/construction.py:498](/conda/pkgs/python_envs/lib/python3.8/site-packages/pandas/core/internals/construction.py#line=497), in nested_data_to_arrays(data, columns, index, dtype)
    495 if is_named_tuple(data[0]) and columns is None:
    496     columns = ensure_index(data[0]._fields)
--> 498 arrays, columns = to_arrays(data, columns, dtype=dtype)
    499 columns = ensure_index(columns)
    501 if index is None:

File [~/conda/pkgs/python_envs/lib/python3.8/site-packages/pandas/core/internals/construction.py:834](/conda/pkgs/python_envs/lib/python3.8/site-packages/pandas/core/internals/construction.py#line=833), in to_arrays(data, columns, dtype)
    832     arr, columns = _list_of_dict_to_arrays(data, columns)
    833 elif isinstance(data[0], ABCSeries):
--> 834     arr, columns = _list_of_series_to_arrays(data, columns)
    835 else:
    836     # last ditch effort
    837     data = [tuple(x) for x in data]

File [~/conda/pkgs/python_envs/lib/python3.8/site-packages/pandas/core/internals/construction.py:877]/conda/pkgs/python_envs/lib/python3.8/site-packages/pandas/core/internals/construction.py#line=876), in _list_of_series_to_arrays(data, columns)
    875     indexer = indexer_cache[id(index)]
    876 else:
--> 877     indexer = indexer_cache[id(index)] = index.get_indexer(columns)
    879 values = extract_array(s, extract_numpy=True)
    880 aligned_values.append(algorithms.take_nd(values, indexer))

AttributeError: 'builtin_function_or_method' object has no attribute 'get_indexer'

**Comment by dinithins** [comment]
Hi @cynthier, A test on 3000 genes alignment runs without any error for me. Could you please provide more info so that I can try to reproduce this error? What are the previous function calls / code segments you had run before calling `aligner.get_stat_df()` in order?

**Comment by cynthier** [comment]
Thanks for your attention @dinithins.

I run the code below following the tutorial. Could you have a look? Thank you for your time!

```import anndata
import numpy as np
import seaborn as sb
import numpy as np
import warnings
import matplotlib.pyplot as plt
import pandas as pd
warnings.filterwarnings("ignore")
from genes2genes import Main
from genes2genes import ClusterUtils
from genes2genes import TimeSeriesPreprocessor
from genes2genes import PathwayAnalyser
from genes2genes import VisualUtils
import optbinning

###
adata_query = anndata.read_h5ad("/Anndata/1_ko_obj.h5ad") # Reference dataset
adata_ref = anndata.read_h5ad("/Anndata/1_con_obj.h5ad")  # Query dataset

### add the log-normalize expression data
con_mat = pd.read_csv("/Anndata/2_Exp_mat_con_G2G.csv")
adata_ref.X = con_mat.transpose()
ko_mat = pd.read_csv("/Anndata/2_Exp_mat_ko_G2G.csv")
adata_query.X = ko_mat.transpose()

###
print(min(adata_ref.obs['time']), max(adata_ref.obs['time']))
print(min(adata_query.obs['time']), max(adata_query.obs['time']))

sb.kdeplot(adata_ref.obs['time'], fill=True, label='Control', color='forestgreen') 
sb.kdeplot(adata_query.obs['time'], fill=True, label='KO', color='midnightblue'); 
plt.xlabel('pseudotime'); plt.legend(); plt.show()

# Set figure size for the notebook
plt.rcParams["figure.figsize"]=12,8
sb.set_theme(style="white")

# Without transparency
sb.kdeplot(data=adata_ref.obs, x="time", hue="sample", cut=0, fill=True, common_norm=False, alpha=0.5)
plt.show()
sb.kdeplot(data=adata_query.obs, x="time", hue="sample", cut=0, fill=True, common_norm=False, alpha=0.5)
plt.show()

from optbinning import ContinuousOptimalBinning

###
x = np.asarray(adata_ref.obs.time)
optb = ContinuousOptimalBinning(name='pseudotime', dtype="numerical")
optb.fit(x, x)
print(len(optb.splits))
x = np.asarray(adata_query.obs.time)
optb = ContinuousOptimalBinning(name='pseudotime', dtype="numerical")
optb.fit(x, x)
print(len(optb.splits))

###
n_bins = 13
sample = "sample"
adata_query.obs["sample"].unique

# define the joint colormap to use for both reference and query
col = np.array(sb.color_palette('colorblind'))[range(5)]
joint_cmap={'A':col[0], 'B':col[1] , 'C':col[2] , 'D':col[3], 'E':col[4]}

VisualUtils.plot_pseudotime_dists_with_interpolation_points(adata_ref, adata_query, n_bins)
VisualUtils.plot_celltype_barplot(adata_ref, n_bins, sample, joint_cmap, legend=True)
VisualUtils.plot_celltype_barplot(adata_query, n_bins, sample, joint_cmap, legend=True)

###
# define the gene list to align
genes = pd.read_csv("/Anndata/3_Genes_G2G.csv")
gene_list = genes.iloc[:,0]
type(genes)

###
aligner = Main.RefQueryAligner(adata_ref, adata_query, gene_list, n_bins) 
aligner.align_all_pairs() 

###
gene_obj = aligner.results_map['SOX10']
alignment_str = gene_obj.alignment_str
print(alignment_str)
print(VisualUtils.color_al_str(alignment_str)) 
print()
print(gene_obj.al_visual)
gene_obj.landscape_obj.plot_alignment_landscape()

VisualUtils.plotTimeSeries('SOX10', aligner, plot_cells=True)
VisualUtils.show_gene_alignment('SOX10', aligner, adata_ref, adata_query, sample, joint_cmap)

aligner.get_aggregate_alignment() 
df = aligner.get_stat_df() 

```

**Comment by dinithins** [comment]
@cynthier This error seems to occur due to passing your gene_list as a `pandas.core.indexes.base.Index` instead of a standard `list`. Could you try again by converting it into a list: `gene_list = list(gene_list)` before passing to `Main.RefQueryAligner()`?

**Comment by cynthier** [comment]
@dinithins Thank you soooooo much! Now they work perfectly!

**Comment by cynthier** [comment]
@dinithins Thank you soooooo much! Now they work perfectly!
