### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by Dooo0k** [Teichlab/Genes2Genes#6]
I keep encountering ModuleNotFoundError for the following imports:
import Main
import ClusterUtils
import TimeSeriesPreprocessor
import PathwayAnalyser
import VisualUtils

The imports above, such as Main, are causing issues, while the ones at the top are working fine. I followed the installation steps exactly as described in the tutorial. How can I resolve this issue?
Thank you.

**Comment by dinithins** [comment]
Hi @Dooo0k, Thanks for spotting this. Please modify the imports as below. 
``` from genes2genes import Main
from genes2genes import ClusterUtils
from genes2genes import TimeSeriesPreprocessor
from genes2genes import PathwayAnalyser
from genes2genes import VisualUtils
```
This has now been fixed in the tutorial notebook.

**Comment by Dooo0k** [comment]
Hi @dinithins , I sincerely appreciate your thorough response.
