### ISSUE TITLE
module 'genes2genes.VisualUtils' has no attribute 'VisualUtils'

### ISSUE THREAD

**Issue by Gh-Genetics** [Teichlab/Genes2Genes#7]
In [11]: joint_cmap = {'ATII': '#ff7f0e', 'ATI': '#2ca02c','Aberrant_Basaloid': '#1f77b4'}
    ...: vs = VisualUtils.VisualUtils.get_celltype_composition_across_time(adata_healthy, adata_disease, n_points=13,
    ...:                                      ANNOTATION_COLNAME='Manuscript_Identity', optimal_binning=False, ref_cmap=joint_cmap, query_cmap=joint_cmap)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 2
      1 joint_cmap = {'ATII': '#ff7f0e', 'ATI': '#2ca02c','Aberrant_Basaloid': '#1f77b4'}
----> 2 vs = VisualUtils.VisualUtils.get_celltype_composition_across_time(adata_healthy, adata_disease, n_points=13, 
      3                                      ANNOTATION_COLNAME='Manuscript_Identity', optimal_binning=False, ref_cmap=joint_cmap, query_cmap=joint_cmap)

AttributeError: module 'genes2genes.VisualUtils' has no attribute 'VisualUtils'

**Comment by dinithins** [comment]
Hello @Gh-Genetics, I believe you have installed the latest Genes2Genes v0.2.0. The above function call is only available in our previous Genes2Genes v0.1.0. All notebooks in https://github.com/Teichlab/G2G_notebooks use v0.1.0 as noted; you will have to use https://github.com/Teichlab/Genes2Genes/releases/tag/v0.1.0 to run those notebooks. 

Please refer to the function calls in [`notebooks/Tutorial.ipynb`](https://github.com/Teichlab/Genes2Genes/blob/main/notebooks/Tutorial.ipynb) to use version 0.2.0.

**Comment by dinithins** [comment]
Thank you so much for your kind words! We are excited to hear that and look forward to seeing Genes2Genes make an impact through diverse applications in the field.
