### ISSUE TITLE
bin_ids are not in the adata_query

### ISSUE THREAD

**Issue by cynthier** [Teichlab/Genes2Genes#9]
Hi, thank you for your great work!

When I run code below, the error is reported.  Is there any step will add the bin_ids to anndata? Thank you.

`VisualUtils.show_gene_alignment(gene, aligner, adata_ref, adata_query, annotation_colname, joint_cmap)`

` AttributeError  Traceback (most recent call last)
/tmp/pbs.1598678.omics/ipykernel_139734/1425815807.py in ?()
----> 1 VisualUtils.show_gene_alignment('SOX10', aligner, adata_ref, adata_query, sample, joint_cmap)

[~/conda/pkgs/python_envs/lib/python3.8/site-packages/genes2genes/VisualUtils.py](/pkgs/python_envs/lib/python3.8/site-packages/genes2genes/VisualUtils.py) in ?(gene, aligner, adata_ref, adata_query, annotation_colname, cmap)
    352 def show_gene_alignment(gene, aligner,  adata_ref, adata_query, annotation_colname, cmap=None):
--> 353     visualize_gene_alignment(aligner.results_map[gene].alignment_str,  adata_ref, adata_query, annotation_colname, cmap=cmap)
    354     plotTimeSeries(gene, aligner, plot_cells=True)
    355     aligner.results_map[gene].alignment_str
    356     print(color_al_str(aligner.results_map[gene].alignment_str))

[~/conda/pkgs/python_envs/lib/python3.8/site-packages/genes2genes/VisualUtils.py](/conda/pkgs/python_envs/lib/python3.8/site-packages/genes2genes/VisualUtils.py) in ?(alignment, adata_ref, adata_query, annotation_colname, cmap)
     50                 cmap = vega_20
     51 
     52             plt.subplot(3,1,1)
     53 
---> 54             metaS = pd.crosstab(adata_ref.obs.bin_ids, adata_ref.obs[annotation_colname])
     55             metaS.apply(lambda x: x*100/sum(x), axis=1).plot(kind='bar',stacked=True,color=cmap, grid = False, legend=False, width=0.7, ax=ax1)
     56 
     57             metaT = pd.crosstab(adata_query.obs.bin_ids, adata_query.obs[annotation_colname])

[~/conda/pkgs/python_envs/lib/python3.8/site-packages/pandas/core/generic.py](/conda/pkgs/python_envs/lib/python3.8/site-packages/pandas/core/generic.py) in ?(self, name)
   5985             and name not in self._accessors
   5986             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987         ):
   5988             return self[name]
-> 5989         return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'bin_ids' `

**Comment by dinithins** [comment]
Hi @cynthier, Thank you for using genes2genes and for your query. `bin_ids` will be added to each anndata object only if the `VisualUtils.plot_celltype_barplot()` plotting function is called as below with a user-defined color map `joint_cmap`.
``` 
VisualUtils.plot_celltype_barplot(adata_ref, n_bins, annotation_colname, joint_cmap)
VisualUtils.plot_celltype_barplot(adata_query, n_bins, annotation_colname, joint_cmap)
```
This is because the bins are defined only for visualisation purposes (i.e. to have an idea of the cell type composition at each interpolation timepoint) -- G2G alignment does not depend on it. Therefore please make sure to run the above before calling ```VisualUtils.show_gene_alignment(gene, aligner, adata_ref, adata_query, annotation_colname, joint_cmap)```.

Could you try this and see if the error goes away? 

Alternatively you could visualise just the alignment and actual cell plots using: 
```
VisualUtils.plotTimeSeries(gene, aligner)
```

**Comment by cynthier** [comment]
Hi @dinithins , now it works well.  Thank you so much for your help.
